# Generated by Django 4.2.6 on 2023-10-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='questions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
