# Generated by Django 3.2.22 on 2023-10-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=0),
        ),
    ]
