# Generated by Django 3.2.22 on 2023-10-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.IntegerField(choices=[('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00'), ('20:00-22:00', '20:00-22:00'), ('22:00-00:00', '22:00-00:00'), ('00:00-02:00', '00:00-02:00')], default=0),
        ),
    ]
