# Generated by Django 3.2.22 on 2023-10-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
