# Generated by Django 3.2.22 on 2023-10-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_delete_yourmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.IntegerField(choices=[(1, '16:00-18:00'), (2, '18:00-20:00'), (3, '20:00-22:00'), (4, '22:00-00:00'), (5, '00:00-02:00')], default=0),
        ),
    ]
